### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by dobesv** [six8/python-clom#1]
Doesn't work in Windows, get an error like:

```
The filename, directory name, or volume label syntax is incorrect.
clom.shell.CommandError: Error while executing "'C:\Program Files (x86)\Ansca\Corona SDK\Corona Simulator.exe' 'F:\proje
cts\corona\testcipr'" (1): Error not captured, see console.
```

I suspect the culprit at this stage is the use of single quotes.  I'll see if it's fixable...

**Comment by dobesv** [comment]
I wonder if it would be feasible to construct an array of arguments and pass them to an appropriate call that takes an argument list, instead of mucking with all this escaping/quoting stuff ... is there some feature you need that relies on the command line being parsed by the shell?

**Comment by six8** [comment]
Clom is one thing I forgot about for cipr. Clom was designed for posix systems. I think it would take a bit more work to work on Windows. Windows programs have different ways of passing parameters but some things like Python expect linux style parameters so it would have to support both and have a smart way to know when to do which.  

Clom's usage in cipr is minor so it would probably be easier to remove it from cipr.

**Comment by dobesv** [comment]
Well, you are already using subprocess.Popen, so in theory all you have to do is pass a sequence of command line parts to it instead of building your own string.  It'll build a string from that itself doing the escaping for you.

**Comment by dobesv** [comment]
BUT i see you are doing some thing like:

s.append('&> /dev/null &')

which of course assumes the command line is processed by the shell ... so, probably not worth the effort to replace stuff like that just to be able to do a cipr run.

**Comment by six8** [comment]
The main place clom is being used is for git commands, zipping and moving files, and running Corona. Git commands and zipping could be done with python libraries while executing Corona could be done with Popen directly. 

When I wrote cipr I wasn't thinking about Windows at all so using clom was easier than using the Python libraries. Some of the commands being run through clom don't map well to Windows equivalents anyway (mv vs move, etc) so not only would I have to worry about escaping things properly on Windows I'd have to translate to related commands. Clom isn't really meant to be that smart. Getting Windows support into cipr will be much easier without clom.

Do you want to give removing clom from cipr a shot as part of your learning process? If not I can tackle it sometime this week.

**Comment by dobesv** [comment]
Ah no worries I'll clean up the Windows issues as I go.

I might be the only one who would benefit.

On Mon, Apr 16, 2012 at 9:39 AM, Mike Thornton <
reply@reply.github.com
