### ISSUE TITLE
translate `long_opt=True` to --long-opt

### ISSUE THREAD

**Issue by bukzor** [six8/python-clom#10]
For example, this does't work as nicely as it might:

``` #!python
print(clom.git(no_pager=True))
git --no_pager
```

``` #!bash
$ git --no_pager                                                                  
Unknown option: --no_pager
```

Because the keyword-option syntax is a convenience feature already, I think it makes sense "to do what I mean" here. As always, if people really want `--no_pager`, they can break down into strings.

**Comment by bukzor** [comment]
There's precedent for this in [ sh.py](http://amoffat.github.io/sh/#keyword-arguments).

**Comment by six8** [comment]
Hm. I guess there's little chance of some command line option actually expecting an underscore. It's probably generally safe to do `.replace('_', '-')`

**Comment by bukzor** [comment]
Yes, that's my suggestion.
